print("Hello World")
print((87+65)*89/78+234-89,"Success")
print()
print()
print("emobilis")
print("Software Dev")
print("Here i come")
print()
print()
print("Our God is an awesome God")
print("He reigns")
print("From Heaven above")
print("With Wisdom")
print("Power")
print("And Love")
print("Our God i an awesome God")
print()
print()
print(78/8)
print(90*0)
